apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: devops-api-claim1
  name: devops-api-claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 30Gi

